title:   Chris Shao
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  <a href="www.linkedin.com/in/zihuan-shao">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br><br>
  <a href="https://chrisshao.notion.site/Portfolio-Chris-Shao-a6e8d9b728ea431e8a1517f55ae5b04e?pvs=4">View My Notion Portfolios</a>
  <br><br><br>
  Results-driven data analyst, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br><br>
  
theme: jekyll-theme-minimal   
 
